// <auto-generated />
using EmployeesService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeesService.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20240130190010_mig3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployeesService.Models.AssignedCoursesModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeesModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeesModelId");

                    b.ToTable("AssignedCourses");
                });

            modelBuilder.Entity("EmployeesService.Models.EmployeesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeesService.Models.AssignedCoursesModel", b =>
                {
                    b.HasOne("EmployeesService.Models.EmployeesModel", "Employee")
                        .WithMany("AssignedCourse")
                        .HasForeignKey("EmployeesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeesService.Models.EmployeesModel", b =>
                {
                    b.Navigation("AssignedCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
