apiVersion: v1
kind: Service
metadata:
  name: gatewayapi-service
spec:
  selector:
    app: ApiGateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP 

---

apiVersion: v1
kind: Service
metadata:
  name: courseapi-service
spec:
  selector:
    app: CoursesService
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: ClusterIP 

---

apiVersion: v1
kind: Service
metadata:
  name: employeeapi-service
spec:
  selector:
    app: EmployeesService
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
