apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ApiGateway
  template:
    metadata:
      labels:
        app: ApiGateway
    spec:
      containers:
        - name: ApiGateway
          image: kubbak/apigateway:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 300m

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: CoursesService
  template:
    metadata:
      labels:
        app: CoursesService
    spec:
      containers:
        - name: CoursesService
          image: kubbak/coursesservice:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: 250m
            requests:
              memory: "512Mi"
              cpu: 200m
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: EmployeesService
  template:
    metadata:
      labels:
        app: EmployeesService
    spec:
      containers:
        - name: EmployeesService
          image: kubbak/employeesservice:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: 500m
            requests:
              memory: "512Mi"
              cpu: 300m

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kubbak/frontend-service:1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 600m
            requests:
              cpu: 400m